-- Create a database and schema if they do not exist
CREATE DATABASE IF NOT EXISTS SAMPLE_DB;
CREATE SCHEMA IF NOT EXISTS SAMPLE_DB.PUBLIC;

-- Create a sample table
CREATE OR REPLACE TABLE SAMPLE_DB.PUBLIC.SAMPLE_TABLE (
    ID NUMBER(38, 0),
    NAME STRING,
    CREATED_AT TIMESTAMP_NTZ
);

-- Load sample data
INSERT INTO SAMPLE_DB.PUBLIC.SAMPLE_TABLE (ID, NAME, CREATED_AT) VALUES
(1, 'Alice', CURRENT_TIMESTAMP()),
(2, 'Bob', CURRENT_TIMESTAMP()),
(3, 'Cara', CURRENT_TIMESTAMP());

-- Verify
SELECT * FROM SAMPLE_DB.PUBLIC.SAMPLE_TABLE
