-- Setup database/schema for AI grant automation
CREATE DATABASE IF NOT EXISTS AI_GOV;
CREATE SCHEMA IF NOT EXISTS AI_GOV.AI_AUTOMATION;

USE DATABASE AI_GOV;
USE SCHEMA AI_AUTOMATION;

-- Request table for free-text prompts and parsed JSON
CREATE OR REPLACE TABLE AI_GRANT_REQUESTS (
  REQUEST_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
  REQUESTED_BY STRING,
  PROMPT_TEXT STRING,
  STATUS STRING DEFAULT 'NEW',
  PARSED_JSON VARIANT,
  PARSE_ERROR STRING,
  APPROVED_BY STRING,
  APPROVED_AT TIMESTAMP_NTZ,
  APPLIED_AT TIMESTAMP_NTZ,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional: grant Cortex capability to the role that will run parsing
-- Requires ACCOUNTADMIN to execute
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AI_TERRAFORM_ROLE;
