USE DATABASE AI_GOV;
USE SCHEMA AI_AUTOMATION;

-- Replace MY_TASK_WH with a warehouse you want to use for the task
CREATE OR REPLACE TASK AI_PARSE_REQUESTS_TASK
  WAREHOUSE = MY_TASK_WH
  SCHEDULE = '5 MINUTE'
AS
  CALL PROCESS_AI_GRANT_REQUESTS();

-- Start the task after creation
ALTER TASK AI_PARSE_REQUESTS_TASK RESUME;
